# Site settings
title: NCKU CSIE 網管日誌
description: '機房申請、雲端申請、連線檢查' # this means to ignore newlines until "baseurl:"
permalink: ':categories:title:month:day'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://jiachanggit.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/img/branding/NCKU.png"
logo-icon: "/assets/img/branding/CSIE.png"
logo-icon-SEO: "/assets/img/branding/CSIE.png" # must be a non SVG file

# Night/Dark mode
# Default mode is "auto", "auto" is for auto nightshift
# (19:00 - 07:00), "manual" is for manual toggle, and
# "on/off" is for default on/off.
#
# Whatever the user's choice is, it will supersede the
# default setting of the site and be kept during the
# visit (session). Only the dark mode setting is "manual",
# it will be always kept on every visit (i.e. no matter
# the browser is closed or not)
night_mode: "auto"

logo-dark: "/assets/img/branding/ncku-title.jpg"
highlight_theme: syntax-base16.monokai.dark # select a dark theme for the code highlighter if needed

# Author settings
author: Jia-Chang # add your name
author-pic: author-pic.jpg
about-author: Human

# Contact links
email: vowevogds@mozmail.com, p76124265@gs.ncku.edu.tw # Add your Email address
phone: # Add your Phone number
website: https://jiachanggit.github.io # Add your website
linkedin: jia81920
github: JiaChangGit # Add your Github handle
twitter:  # Add your Twitter handle
bandcamp:  # Add your Bandcamp username
stackoverflow:  # Add your stackoverflow account

# Newsletter
#mailchimp: "https://github.us1.list-manage.com/subscribe/post?u=8ece198b3eb260e6838461a60&amp;id=397d90b5f4"

# Tracker
analytics:
fbadmin:

# Paginate
paginate: 6
paginate_path: 'page:num'
words_per_minute: 100

extensions:
  mermaid_enable: true

# Comments
comments: utteranc  #[disqus, utteranc]
comments_opts:
  comments_curtain: yes # leave empty to show the disqus embed directly
  repo: JiaChangGit/JiaChangGit.github.io # The GitHub repo URL.  https://utteranc.es/
  issue_term: pathname # The GitHub issue label
  label: comment # The GitHub comments label
  theme: github-light # The GitHub comment's there. e.g. github-dark
  # Disqus
  discus_identifier: # Add your discus identifier

# Build settings
markdown: kramdown
mathjax: true
highlighter: rouge
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

# Outputting
timezone: Asia/Taipei # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

category_archive:
  type: liquid
  path: /categories/

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
